### ISSUE TITLE
unfinished/examine-firefox-places.sqlite.sh hint

### ISSUE THREAD

**Issue by tuxjobs** [spiralofhope/shell-random#1]
This will probably help you: http://www.commandlinefu.com/commands/view/14088/get-your-firefox-bookmarks

**Comment by spiralofhope** [comment]
Thank's for tanking the time to post that.

I'm still vaguely interested in using this script, so I updated it with my goals.

---

For my reference:

For https://github.com/spiralofhope/shell-random/blob/master/unfinished/examine-firefox-places.sqlite.sh

([source](http://www.commandlinefu.com/commands/view/14088/get-your-firefox-bookmarks))

``` bash
sqlite3 \
  ~/.mozilla/firefox/*.[dD]efault/places.sqlite \
  "SELECT strftime('%d.%m.%Y %H:%M:%S', dateAdded/1000000, 'unixepoch', 'localtime'),url \
  FROM moz_places, moz_bookmarks \
  WHERE moz_places.id = moz_bookmarks.fk \
  ORDER BY dateAdded;"
```

> Extracts yours bookmarks out of sqlite with the format:
> dateAdded|url
